name: A_E_Guitar_Recognition-312

channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  - jupyterlab=4.5
  - librosa=0.11
  - matplotlib=3.10
  - numpy=2.2
  - pandas=2.3
  - pip=26.0
  - pip:
    - soundfile==0.13
    - scikit-learn==1.8
  - pydub=0.25
  - python-sounddevice=0.5
  - pytorch=2.6
  - pytorch-cuda=12.4
  - scipy=1.17
  - sox=14.4
  - torchaudio=2.6
  - torchvision=0.21



